name: Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x
          opam-depext-flags: --with-test

      - run: opam pin add -y .
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune exec src/blogger.exe -- build
